// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
  [DbContext(typeof(DataContext))]
  partial class DataContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

      modelBuilder.Entity("API.Entity.AppUser", b =>
          {
            b.Property<int>("id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<string>("user_name")
                      .HasColumnType("TEXT");

            b.HasKey("id");

            b.ToTable("user");
          });
#pragma warning restore 612, 618
    }
  }
}
